-- =====================================================================
-- FILTER: APPENDIX NUMBERING NORMALIZATION FOR PANDOC HTML OUTPUT
-- =====================================================================
-- This Lua filter rewrites appendix heading numbering and internal
-- cross-reference text for HTML generated by Pandoc from LaTeX input.
-- It is specifically intended to correct the mismatch between LaTeX
-- appendix semantics (e.g., Appendix A / A.1 / A.1.2) and Pandoc's
-- default HTML rendering, which may otherwise flatten appendices into
-- ordinary numeric sections (e.g., 13 / 13.1 / 13.1.2).
--
-- The filter performs two primary functions:
--   1. It rewrites appendix headers in the document body so that
--      top-level appendix sections display as "Appendix A." or
--      "Appendix B.", while lower-level headings display as A.1,
--      A.1.1, etc.
--   2. It rewrites internal link text for references targeting appendix
--      labels so that body references display the normalized appendix
--      numbering instead of the default numeric form.
--
-- This implementation assumes appendix labels follow a stable pattern
-- such as "sec:appendix-a-..." and "sec:appendix-b-...". It also
-- tolerates source headings that already contain manual numbering and
-- strips those prefixes before inserting normalized numbering.
-- =====================================================================

-- ---------------------------------------------------------------------
-- GLOBAL APPENDIX REFERENCE MAP
-- ---------------------------------------------------------------------
-- Stores the normalized display value for each appendix header ID after
-- header traversal. This map is later used during link rewriting so
-- that internal references targeting appendix anchors can be replaced
-- with the correct appendix-style numbering.
-- ---------------------------------------------------------------------
local appendix_map = {}

-- ---------------------------------------------------------------------
-- HELPER: STRINGIFY PANDOC INLINE CONTENT
-- ---------------------------------------------------------------------
-- Converts a Pandoc inline or block content structure into plain text
-- using pandoc.utils.stringify(). This is used throughout the filter
-- whenever header content or link text must be interpreted as a normal
-- string for pattern matching or reconstruction.
-- ---------------------------------------------------------------------
local function stringify(x)
  return pandoc.utils.stringify(x)
end

-- ---------------------------------------------------------------------
-- HELPER: TRIM LEADING / TRAILING WHITESPACE
-- ---------------------------------------------------------------------
-- Normalizes text by removing leading and trailing whitespace. This is
-- applied before and after pattern-based prefix stripping so that
-- reconstructed header titles remain clean and deterministic.
-- ---------------------------------------------------------------------
local function trim(s)
  return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

-- ---------------------------------------------------------------------
-- HELPER: DERIVE APPENDIX LETTER FROM LABEL ID
-- ---------------------------------------------------------------------
-- Extracts the appendix designator (e.g., "A" or "B") from a label ID
-- that follows the established pattern "sec:appendix-a-..." or
-- "sec:appendix-b-...". If the ID does not match the expected appendix
-- label model, nil is returned and the calling logic treats the header
-- or link as non-appendix content.
-- ---------------------------------------------------------------------
local function appendix_letter_from_id(id)
  if not id then
    return nil
  end
  local a = id:match("^sec:appendix%-([a-z])%-")
  if a then
    return string.upper(a)
  end
  return nil
end

-- ---------------------------------------------------------------------
-- HELPER: STRIP MANUAL APPENDIX PREFIXES FROM TITLES
-- ---------------------------------------------------------------------
-- Removes manual numbering that may already be embedded in appendix
-- titles in the LaTeX source before the filter inserts normalized
-- numbering. This supports source patterns such as:
--   - "Appendix A. Title"
--   - "A.1 Title"
--   - "A.1.2 Title"
--   - "A.1.2.3 Title"
--
-- The function intentionally handles both top-level appendix labels and
-- lower-level numbered subsection forms so that duplicate numbering is
-- not introduced in the rendered HTML headers or TOC entries.
-- ---------------------------------------------------------------------
local function strip_manual_prefix(text, letter)
  text = trim(text)

  -- Top-level appendix titles:
  -- "Appendix A. Title"
  -- "Appendix A Title"
  -- "appendix A. Title"
  local appendix_pat = "^%s*[Aa]ppendix%s+" .. letter .. "%.?"
  if text:match(appendix_pat) then
    text = text:gsub(appendix_pat .. "%s*", "", 1)
  end

  -- Numbered appendix subsection titles:
  -- "A.1 Title"
  -- "A.1.2 Title"
  -- "A.1.2.3 Title"
  text = text:gsub("^" .. letter .. "%.%d+%.%d+%.%d+%.?%s+", "", 1)
  text = text:gsub("^" .. letter .. "%.%d+%.%d+%.?%s+", "", 1)
  text = text:gsub("^" .. letter .. "%.%d+%.?%s+", "", 1)

  return trim(text)
end

-- ---------------------------------------------------------------------
-- HELPER: BUILD NORMALIZED HEADER CONTENT
-- ---------------------------------------------------------------------
-- Constructs the replacement inline content for appendix headers. For
-- top-level appendix sections, the visible prefix is rendered as
-- "Appendix A." or "Appendix B." within a header-section-number span so
-- that the heading and TOC remain visually aligned with Pandoc's normal
-- numbered-header structure. For lower-level headings, only the compact
-- numeric form (e.g., "A.2.4") is emitted before the title text.
-- ---------------------------------------------------------------------
local function make_header_content(number, title_text, is_appendix_top)
  if is_appendix_top then
    return {
      pandoc.Span(
        { pandoc.Str("Appendix"), pandoc.Space(), pandoc.Str(number .. ".") },
        pandoc.Attr("", { "header-section-number" })
      ),
      pandoc.Space(),
      pandoc.Str(title_text)
    }
  else
    return {
      pandoc.Span(
        { pandoc.Str(number) },
        pandoc.Attr("", { "header-section-number" })
      ),
      pandoc.Space(),
      pandoc.Str(title_text)
    }
  end
end

-- ---------------------------------------------------------------------
-- PASS 1: COLLECT APPENDIX IDS AND REWRITE HEADERS
-- ---------------------------------------------------------------------
-- Traverses document headers in order, detects appendix scope based on
-- label IDs, maintains per-appendix counters, records normalized values
-- in appendix_map, and rewrites the visible header text accordingly.
--
-- Behavior:
--   - Level 1 appendix headers become "Appendix A." / "Appendix B."
--   - Level 2 headers become "A.1", "A.2", etc.
--   - Level 3 headers become "A.1.1", "A.2.4", etc.
--   - Level 4 headers are also supported for completeness.
--
-- This pass is authoritative for numbering state. The later link pass
-- depends entirely on the values stored here.
-- ---------------------------------------------------------------------
local function collect_and_rewrite_headers(doc)
  local current_appendix = nil
  local counters = {}

  for _, block in ipairs(doc.blocks) do
    if block.t == "Header" then
      local id = block.identifier
      local letter = appendix_letter_from_id(id)

      -- ---------------------------------------------------------------
      -- LEVEL 1: TOP-LEVEL APPENDIX SECTION
      -- ---------------------------------------------------------------
      -- Establishes appendix scope, resets counters for that appendix,
      -- stores the top-level appendix letter in the map, strips any
      -- manual "Appendix A." prefix from the source title, and rewrites
      -- the header so the visible form becomes "Appendix A. <Title>".
      -- ---------------------------------------------------------------
      if block.level == 1 and letter then
        current_appendix = letter
        counters[letter] = { subsection = 0, subsubsection = 0, level4 = 0 }
        appendix_map[id] = letter

        local raw = trim(stringify(block.content))
        local title = raw:gsub("^%s*[Aa]ppendix%s+" .. letter .. "%.?" .. "%s*", "", 1)
        title = trim(title)

        block.content = make_header_content(letter, title, true)

      -- ---------------------------------------------------------------
      -- LEVEL 2: APPENDIX SUBSECTION
      -- ---------------------------------------------------------------
      -- Increments the subsection counter within the active appendix,
      -- resets deeper counters, records the normalized value (e.g.,
      -- "A.2"), strips any manual numbering from the title, and rewrites
      -- the header with the normalized appendix subsection prefix.
      -- ---------------------------------------------------------------
      elseif current_appendix
        and block.level == 2
        and id ~= ""
        and appendix_letter_from_id(id) == current_appendix
      then
        local c = counters[current_appendix]
        c.subsection = c.subsection + 1
        c.subsubsection = 0
        c.level4 = 0

        local num = string.format("%s.%d", current_appendix, c.subsection)
        appendix_map[id] = num

        local title = strip_manual_prefix(stringify(block.content), current_appendix)
        block.content = make_header_content(num, title, false)

      -- ---------------------------------------------------------------
      -- LEVEL 3: APPENDIX SUBSUBSECTION
      -- ---------------------------------------------------------------
      -- Increments the subsubsection counter within the active appendix
      -- subsection, resets level-4 counters, records the normalized
      -- value (e.g., "A.2.4"), strips manual numbering from the source
      -- title, and rewrites the visible header content.
      -- ---------------------------------------------------------------
      elseif current_appendix
        and block.level == 3
        and id ~= ""
        and appendix_letter_from_id(id) == current_appendix
      then
        local c = counters[current_appendix]
        c.subsubsection = c.subsubsection + 1
        c.level4 = 0

        local num = string.format("%s.%d.%d", current_appendix, c.subsection, c.subsubsection)
        appendix_map[id] = num

        local title = strip_manual_prefix(stringify(block.content), current_appendix)
        block.content = make_header_content(num, title, false)

      -- ---------------------------------------------------------------
      -- LEVEL 4: OPTIONAL DEEPER APPENDIX HEADING SUPPORT
      -- ---------------------------------------------------------------
      -- Supports an additional heading depth if present. This is not
      -- strictly required for the current document structure but is
      -- included for completeness and consistency in case a deeper
      -- appendix hierarchy is introduced later.
      -- ---------------------------------------------------------------
      elseif current_appendix
        and block.level == 4
        and id ~= ""
        and appendix_letter_from_id(id) == current_appendix
      then
        local c = counters[current_appendix]
        c.level4 = c.level4 + 1

        local num = string.format(
          "%s.%d.%d.%d",
          current_appendix, c.subsection, c.subsubsection, c.level4
        )
        appendix_map[id] = num

        local title = strip_manual_prefix(stringify(block.content), current_appendix)
        block.content = make_header_content(num, title, false)
      end
    end
  end

  return doc
end

-- ---------------------------------------------------------------------
-- PASS 2: REWRITE INTERNAL LINK TEXT FOR APPENDIX REFERENCES
-- ---------------------------------------------------------------------
-- Rewrites link text for internal links that target appendix IDs found
-- in appendix_map. This preserves the original anchor target while
-- changing only the visible link text.
--
-- Supported visible input forms include:
--   - "13"
--   - "13.1"
--   - "13.1.2"
--   - "Section 13.1.2"
--   - "Appendix 13"
--
-- These are rewritten to the normalized appendix forms recorded during
-- the header pass, such as:
--   - "A"
--   - "A.1"
--   - "A.1.2"
--   - "Section A.1.2"
--   - "Appendix A"
-- ---------------------------------------------------------------------
local function rewrite_link_text(link)
  local target = link.target or ""
  local id = target:match("^#(.+)$")
  if not id then
    return link
  end

  local appendix_num = appendix_map[id]
  if not appendix_num then
    return link
  end

  local text = stringify(link.content)

  -- ---------------------------------------------------------------
  -- CASE 1: BARE NUMERIC REFERENCE
  -- ---------------------------------------------------------------
  -- Rewrites plain numeric link text such as "13", "13.1", or "13.1.2"
  -- to the normalized appendix form (e.g., "A", "A.1", "A.1.2").
  -- ---------------------------------------------------------------
  if text:match("^%d+$")
    or text:match("^%d+%.%d+$")
    or text:match("^%d+%.%d+%.%d+$")
    or text:match("^%d+%.%d+%.%d+%.%d+$")
  then
    link.content = { pandoc.Str(appendix_num) }
    return link
  end

  -- ---------------------------------------------------------------
  -- CASE 2: "SECTION N..." STYLE REFERENCE
  -- ---------------------------------------------------------------
  -- Rewrites visible link text of the form "Section 13.1.2" to
  -- "Section A.1.2" while preserving the internal anchor target.
  -- ---------------------------------------------------------------
  if text:match("^Section%s+%d+[%d%.]*$") then
    link.content = {
      pandoc.Str("Section"),
      pandoc.Space(),
      pandoc.Str(appendix_num)
    }
    return link
  end

  -- ---------------------------------------------------------------
  -- CASE 3: "APPENDIX N..." STYLE REFERENCE
  -- ---------------------------------------------------------------
  -- Rewrites visible link text of the form "Appendix 13" to
  -- "Appendix A" when the target is a top-level appendix section.
  -- If the stored value is deeper than a single appendix letter, the
  -- compact appendix-style number is used directly.
  -- ---------------------------------------------------------------
  if text:match("^Appendix%s+%d+[%d%.]*$") then
    local visible = appendix_num:match("^[A-Z]$") and ("Appendix " .. appendix_num) or appendix_num
    link.content = { pandoc.Str(visible) }
    return link
  end

  return link
end

-- ---------------------------------------------------------------------
-- FILTER ENTRY POINT: DOCUMENT-LEVEL TWO-PASS TRANSFORMATION
-- ---------------------------------------------------------------------
-- Executes the filter as a document-level transformation. The first
-- pass rewrites appendix headers and records normalized numbering in the
-- appendix_map. The second pass walks the document and rewrites any
-- qualifying internal links that target those appendix IDs. This order
-- is required so that all appendix numbering is known before link text
-- replacement occurs.
-- ---------------------------------------------------------------------
function Pandoc(doc)
  doc = collect_and_rewrite_headers(doc)
  doc = doc:walk({
    Link = rewrite_link_text
  })
  return doc
end
